# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b17ffc43f6648d815ceb9331a36efa73a8f7576f3ef27edde45b6656a7b761906a355a011419b4041326164685a16e58267f1cc44b0e709473eaa5af0ea4eef5

test:
  secret_key_base: 9feae0e51b0d482b72462205ae4c6905920b289be67d984228de7aa4a376b5186f9f5f982237bff61c3dff3593f1b4205944529d03376599c42ec99f49ebf824

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
